# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    - name: Copy Jar file to EC2 via SSH Key
      uses: appleboy/scp-action@master
      with:
        host: ec2-52-53-220-104.us-west-1.compute.amazonaws.com
        username: ec2-user
        port: 22
        key: ${{ secrets.KEY }}
        source: "target/cs480-1.0.jar"
        target: "~/"

    - name: Run commands to start the Java server
          uses: appleboy/ssh-action@v0.1.9
          with:
            host: ec2-52-53-220-104.us-west-1.compute.amazonaws.com
            username: ec2-user
            key: ${{ secrets.KEY }}
            port: 22
            script: |
              killall java
              nohup java -jar /home/ec2-user/target/cs480-1.0.jar > log.txt &
              sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
              sudo iptables -I INPUT -p tcp --dport 8080 -j ACCEPT
